/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Appointment;
import model.VitalSigns;

/**
 *
 * @author user
 */
public class ViewPatientsForDoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientsJPanel
     */
    LoginJPanel loginPanel = new LoginJPanel();
    Appointment docAppoint = new Appointment();
    VitalSigns vs = new VitalSigns();
    public ViewPatientsForDoctorJPanel() {
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewPatients = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        lblTemperature = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        btnAddVitalSigns = new javax.swing.JButton();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblViewPatients.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        tblViewPatients.setForeground(new java.awt.Color(51, 51, 255));
        tblViewPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient Name", "Community", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewPatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewPatientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewPatients);

        jLabel1.setFont(new java.awt.Font("Centaur", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Add Vital Signs");

        txtTemperature.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        txtTemperature.setForeground(new java.awt.Color(51, 51, 255));

        lblTemperature.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        lblTemperature.setForeground(new java.awt.Color(51, 51, 255));
        lblTemperature.setText("Temperature");

        lblBloodPressure.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        lblBloodPressure.setForeground(new java.awt.Color(51, 51, 255));
        lblBloodPressure.setText("Blood Pressure");

        txtBloodPressure.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        txtBloodPressure.setForeground(new java.awt.Color(51, 51, 255));

        btnAddVitalSigns.setBackground(new java.awt.Color(155, 211, 248));
        btnAddVitalSigns.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        btnAddVitalSigns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-1-icon.png"))); // NOI18N
        btnAddVitalSigns.setText("ADD");
        btnAddVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVitalSignsActionPerformed(evt);
            }
        });

        lblPatientName.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(51, 51, 255));
        lblPatientName.setText("Patient Name");

        txtPatientName.setFont(new java.awt.Font("Centaur", 0, 14)); // NOI18N
        txtPatientName.setForeground(new java.awt.Color(51, 51, 255));

        lblTitle.setFont(new java.awt.Font("Centaur", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 255));
        lblTitle.setText("Patient Diagnosis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTemperature)
                                    .addComponent(lblBloodPressure)
                                    .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTemperature)
                                    .addComponent(txtBloodPressure)
                                    .addComponent(txtPatientName, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addGap(123, 123, 123)
                                .addComponent(btnAddVitalSigns))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 198, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnAddVitalSigns))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPatientName)
                            .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTemperature))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodPressure)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblViewPatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewPatientsMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = tblViewPatients.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this,"please select a row");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblViewPatients.getModel();
        
        Appointment selectedPatient = (Appointment) model.getValueAt(selectedRowIndex, 0);
        System.out.println("=====VIEW PATIENTS FOR DOCTORS==========");
        System.out.println("Patient name= "+selectedPatient.getPatientName()+"Patient city= "+selectedPatient.getPatientCommunity());
        
        txtPatientName.setText(selectedPatient.getPatientName());
    }//GEN-LAST:event_tblViewPatientsMouseClicked

    private void btnAddVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVitalSignsActionPerformed
        // TODO add your handling code here:
        String patientName = txtPatientName.getText();
        String doctorName = loginPanel.getDoctorName();
        
        System.out.println("Patient name- "+patientName+"Doctor name- "+doctorName);
        
        Double temp = Double.parseDouble(txtTemperature.getText());
        Double bp = Double.parseDouble(txtBloodPressure.getText());
        vs.addNewVitalSigns(patientName, doctorName, temp, bp);
        JOptionPane.showMessageDialog(this,"Vital Signs added for "+patientName);
    }//GEN-LAST:event_btnAddVitalSignsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVitalSigns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblViewPatients;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblViewPatients.getModel();
        model.setRowCount(0);
        
        for(Appointment docAppoint: Appointment.getBookAppointment()){
            Object[] row = new Object[3];
            row[0] = docAppoint;
            row[1] = docAppoint.getPatientCommunity();
            row[2] = docAppoint.getPatientAge();
            
            model.addRow(row);
        }       
    }
}
